import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./NavBar/page";
import SubscribeComponent from "./Subscribe/page"; 
import Footer from './Footer/page'

export const metadata: Metadata = {
  title: "Mekark",
  icons: {
    icon: '/Navbarimages/Logo.svg', // Path to your favicon
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Persistent Navbar */}
        <Navbar />

        {/* Page Content */}
        <main>{children}</main>

        {/* Subscribe Component */}
        <div style={{ padding: "2rem 0" }}>
          <SubscribeComponent />
        </div>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
